# See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

# This stage is used when running from VS in fast mode (Default for Debug configuration)
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER app
WORKDIR /app
EXPOSE 8080
EXPOSE 8081


# This stage is used to build the service project
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
RUN apt-get update && apt-get install -y curl
RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
RUN apt-get install -y nodejs
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["./finalvirtualbot.client/nuget.config", "finalvirtualbot.client/"]
COPY ["FinalVirtualBot.Server/FinalVirtualBot.Server.csproj", "FinalVirtualBot.Server/"]
COPY ["./finalvirtualbot.client/finalvirtualbot.client.esproj", "finalvirtualbot.client/"]
RUN dotnet restore "./FinalVirtualBot.Server/FinalVirtualBot.Server.csproj"
COPY . .
WORKDIR "/src/FinalVirtualBot.Server"
RUN dotnet build "FinalVirtualBot.Server.csproj" -c $BUILD_CONFIGURATION -o /app/build

# This stage is used to publish the service project to be copied to the final stage
FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./FinalVirtualBot.Server.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

# This stage is used in production or when running from VS in regular mode (Default when not using the Debug configuration)
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "FinalVirtualBot.Server.dll"]